# Codec can't encode character

## Fixed

My original solution to the below was to wrap the `foldername()` func around any folder names being sent to output.

The new solution involves renaming `foldername()` to `cleanse_output()` and applying it at the extremely few points of output, rather than trying to catch each possible dodgy input.

```sh
dup -vvv
```

```text
Traceback (most recent call last):
 File "c:\users\pete\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
   return _run_code(code, main_globals, None,
 File "c:\users\pete\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
   exec(code, run_globals)
 File "C:\Users\Pete\AppData\Local\Programs\Python\Python39\Scripts\dup.exe\__main__.py", line 7, in <module>
 File "c:\users\pete\appdata\local\programs\python\python39\lib\site-packages\dup\command_line.py", line 63, in main
   duplicates.find()
 File "c:\users\pete\appdata\local\programs\python\python39\lib\site-packages\dup\duplicates.py", line 10, in find
   by_hash = find_duplicates()
 File "c:\users\pete\appdata\local\programs\python\python39\lib\site-packages\dup\duplicates.py", line 22, in find_duplicates
   by_size = recurse_into_folder('.')
 File "c:\users\pete\appdata\local\programs\python\python39\lib\site-packages\dup\__init__.py", line 37, in recurse_into_folder
   recurse_into_folder(entry.path, by_size)
 File "c:\users\pete\appdata\local\programs\python\python39\lib\site-packages\dup\__init__.py", line 37, in recurse_into_folder
   recurse_into_folder(entry.path, by_size)
 File "c:\users\pete\appdata\local\programs\python\python39\lib\site-packages\dup\__init__.py", line 37, in recurse_into_folder
   recurse_into_folder(entry.path, by_size)
 [Previous line repeated 1 more time]
 File "c:\users\pete\appdata\local\programs\python\python39\lib\site-packages\dup\__init__.py", line 17, in recurse_into_folder
   output(f"Searching in {dir}", Verbosity.Information)
 File "c:\users\pete\appdata\local\programs\python\python39\lib\site-packages\dup\__init__.py", line 43, in output
   print("  "*level + string)
 File "c:\users\pete\appdata\local\programs\python\python39\lib\encodings\cp1252.py", line 19, in encode
   return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\uf022' in position 68: character maps to <undefined>
```

Actually seems to be triggered by the following folder: `F:\__Photos__\_unsorted_\From Macbook\Unsorted From Documents\USAï€¢Mexico Photos`.

## Details

This seems to be windows-specific (the folder in question came from an iMac to a Windows machine; the name has apparently been converted from Unicode (Mac OS X) to CP1252 (Windows 10) and hence needs to be converted back!)

## Reopened

The same error occurred here:

```err
Archiving duplicates
Archiving: [                                        ] 0.1% 85 of 60167Traceback (most recent call last):
  File "c:\users\pete\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\pete\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Pete\AppData\Local\Programs\Python\Python39\Scripts\dup.exe\__main__.py", line 7, in <module>
  File "c:\users\pete\appdata\local\programs\python\python39\lib\site-packages\dup\command_line.py", line 104, in main
    duplicates.archive()
  File "c:\users\pete\appdata\local\programs\python\python39\lib\site-packages\dup\duplicates.py", line 19, in archive
    archive_duplicates(by_hash)
  File "c:\users\pete\appdata\local\programs\python\python39\lib\site-packages\dup\duplicates.py", line 151, in archive_duplicates
    copy_to(archive_folder, by_hash[size][hash][index])
  File "c:\users\pete\appdata\local\programs\python\python39\lib\site-packages\dup\duplicates.py", line 179, in copy_to
    archive_log(folder, file_path, tfn, 'copied')
  File "c:\users\pete\appdata\local\programs\python\python39\lib\site-packages\dup\duplicates.py", line 194, in archive_log
    f.write(f"[{target}] {action} from [{source}]\n")
  File "c:\users\pete\appdata\local\programs\python\python39\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\uf022' in position 80: character maps to <undefined>
```
